### ISSUE TITLE
Ignore switch

### ISSUE THREAD

**Issue by dvandersluis** [codeclimate/codeclimate-bundler-audit#24]
Is there any way to specify issues to ignore, like can be done with the `--ignore` switch to bundle-audit on the command line?

**Comment by ABaldwinHunter** [comment]
Hi @dvandersluis! You can disable bundler-audit checks in your .codeclimate.yml like so:

`.codeclimate.yml`
```YAML
engines:
  bundler-audit:
    enabled: true
    checks:
      Insecure Dependency:
        enabled: false
```

If you'd like to ignore a particular issue found, you may use its fingerprint, as calculated by Code Climate during analysis:

```YAML
engines:
  bundler-audit:
    enabled: true
    exclude_fingerprints:
    - 75b66bdd34caff8e7a281287e3b22db2
```
